"""phase2 task depth: dates, time, recurrence, approval, watchers, dependencies

Revision ID: 129e4bd91d7b
Revises: 868bce4a152d
Create Date: 2026-06-05 14:10:40.674990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129e4bd91d7b'
down_revision: Union[str, None] = '868bce4a152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


recurrence_enum = sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='recurrencetype')
approval_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ADD COLUMN does not auto-create Postgres ENUM types; create them explicitly first.
    bind = op.get_bind()
    recurrence_enum.create(bind, checkfirst=True)
    approval_enum.create(bind, checkfirst=True)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    op.create_table('task_watchers',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.add_column('tasks', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('estimate_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('logged_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='recurrencetype', create_type=False), nullable=False, server_default='NONE'))
    op.add_column('tasks', sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tasks', sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus', create_type=False), nullable=True))
    # Drop the server defaults now that existing rows are backfilled (app supplies values going forward).
    op.alter_column('tasks', 'recurrence', server_default=None)
    op.alter_column('tasks', 'requires_approval', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'approval_status')
    op.drop_column('tasks', 'requires_approval')
    op.drop_column('tasks', 'recurrence')
    op.drop_column('tasks', 'logged_hours')
    op.drop_column('tasks', 'estimate_hours')
    op.drop_column('tasks', 'start_date')
    op.drop_table('task_watchers')
    op.drop_table('task_dependencies')
    bind = op.get_bind()
    recurrence_enum.drop(bind, checkfirst=True)
    approval_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
