"""Add timestamps to notes and requests

Revision ID: 23fdcb54f2a0
Revises: 66b01cb62bad
Create Date: 2026-06-04 19:35:23.134212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fdcb54f2a0'
down_revision: Union[str, None] = '66b01cb62bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('admin_requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('admin_requests', 'updated_at')
    op.drop_column('admin_requests', 'created_at')
    # ### end Alembic commands ###
