"""add_access_token_v3

Revision ID: 7de2cd491f02
Revises: 307090203f7b
Create Date: 2026-06-04 09:46:04.698682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de2cd491f02'
down_revision: Union[str, None] = '307090203f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_integrations', sa.Column('access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_integrations', 'access_token')
    # ### end Alembic commands ###
