"""Add multiple assignees support

Revision ID: 868bce4a152d
Revises: 7dd1f8cd60cf
Create Date: 2026-06-04 23:10:26.397368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868bce4a152d'
down_revision: Union[str, None] = '7dd1f8cd60cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.drop_table('task_assignees')
    # ### end Alembic commands ###
